import { toSlug } from "src/lib/utils"

export const headerMenus =  [
  {
    name: "Today's Deal",
    href: '/search?tag=todays-deal',
  },
  {
    name: 'Completed Orders',
    href: '/search?tag=completed-orders',
  },
  {
    name: 'Favourites',
    href: '/search?tag=favourites',
  },
  {
    name: 'Subscriptions',
    href: '/search?tag=subcriptions',
  },
  {
    name: 'Customer Service',
    href: '/page/customer-service',
  },
  // {
  //   name: 'About Us',
  //   href: '/page/about-us',
  // },
  // {
  //   name: 'Help',
  //   href: '/page/help',
  // },
]

export const products = [
  {
    name: 'Onion',
    slug: toSlug('Onion'),
    category: 'General',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732183603/ahisi/1732183602881_produce.jpg", '/images/p11-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 3000,
    listPrice: 0,
    brand: 'Onion',
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      'Onions are versatile root vegetables known for their sharp flavor, aroma, and health benefits. Available in red, and white varieties.',
    // sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Brown'],
    options: [
      {
        name: "1kg",
        price: 3000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732183603/ahisi/1732183602881_produce.jpg",
        countInStock: 50,
      },
      {
        name: "2kg",
        price: 5500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732183603/ahisi/1732183602881_produce_2kg.jpg",
        countInStock: 30,
      },
      {
        name: "5kg",
        price: 12000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732183603/ahisi/1732183602881_produce_5kg.jpg",
        countInStock: 20,
      },
    ],

    reviews: [],
  },
  {
    _id: "66ec2b2abc0e9f3ea6616686",
    name: "Riverbite",
    slug: "riverbite",
    category: "6769a979015abc57a03ec8b5",
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732000738/ahisi/1732000738261_produce_20241119_081636_0000.jpg"], // Default image
    brand: "Riverbite",
    description: "Riverbite is a premium smoked catfish snack set apart by superior quality and careful preparation. Each package contains four expertly degutted catfish cutlets.",
    price: 5850, // Default price
    listPrice: 5850,
    countInStock: 50, // Total stock across all options
    tags: ["best-seller", "todals-deal"],
    colors: [], // No colors for smoked catfish
    sizes: [], // No sizes for smoked catfish
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    isPublished: true,
    reviews: [],
    createdAt: "2025-01-28T13:56:48.184Z",
    updatedAt: "2024-11-28T14:29:10.916Z",
    options: [
      {
        name: "Standard Pack",
        price: 5850,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732000738/ahisi/1732000738261_produce_20241119_081636_0000.jpg",
        countInStock: 50,
      },
    ],
  },
  {
    name: 'Apple',
    slug: toSlug('Apple'),
    category: 'Fruits',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732372960/ahisi/1732372957967_1732110649466_produce-1.jpg"],
    tags: ['new-arrival'],
    isPublished: true,
    price: 650,
    listPrice: 650,
    brand: 'Local Farm',
    avgRating: 4.5,
    numReviews: 5,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 2 },
    ],
    numSales: 7,
    countInStock: 20,
    description: 'Apples are versatile, and used in snacks, baking, and juices. They come in various colors and are rich in fiber, vitamin C, and antioxidants.',
    colors: ['Red', 'Green', 'Yellow'],
    options: [
      {
        name: "1kg",
        price: 650,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732372960/ahisi/1732372957967_1732110649466_produce-1.jpg",
        countInStock: 20,
      },
      {
        name: "2kg",
        price: 1200,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732372960/ahisi/1732372957967_1732110649466_produce-1_2kg.jpg",
        countInStock: 15,
      },
    ],
    reviews: [],
  },
  {
    name: 'Pineapple',
    slug: toSlug('Pineapple'),
    category: 'Fruits',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732136297/ahisi/1732136297347_produce-2.jpg"],
    tags: ['new-arrival', "todals-deal"],
    isPublished: true,
    price: 1550,
    listPrice: 1550,
    brand: 'Tropical Farms',
    avgRating: 4.8,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 6 },
    ],
    numSales: 12,
    countInStock: 25,
    description: 'Pineapple is a tropical fruit with a sweet, tangy flavor and high in Vitamin C, fiber, and antioxidants. It is enjoyed fresh or in various dishes like smoothies, desserts, and juices.',
    colors: ['Yellow'],
    options: [
      {
        name: "1 piece",
        price: 1550,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732136297/ahisi/1732136297347_produce-2.jpg",
        countInStock: 25,
      },
      {
        name: "2 pieces",
        price: 3000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732136297/ahisi/1732136297347_produce-2_2pieces.jpg",
        countInStock: 10,
      },
    ],
    reviews: [],
  },
  {
    name: 'Orange',
    slug: toSlug('Orange'),
    category: 'Fruits',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732429967/ahisi/1732429966569_produce-26.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 150,
    listPrice: 150,
    brand: 'Citrus Farms',
    avgRating: 4.6,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 4 },
    ],
    numSales: 15,
    countInStock: 50,
    description: 'Oranges are often eaten fresh, juiced, or used in cooking and baking. They are a popular choice for boosting immunity and promoting hydration.',
    colors: ['Orange'],
    options: [
      {
        name: "1kg",
        price: 150,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732429967/ahisi/1732429966569_produce-26.jpg",
        countInStock: 50,
      },
      {
        name: "5kg",
        price: 700,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732429967/ahisi/1732429966569_produce-26_5kg.jpg",
        countInStock: 20,
      },
    ],
    reviews: [],
  },
  {
    name: 'Watermelon',
    slug: toSlug('Watermelon'),
    category: 'Fruits',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732184338/ahisi/1732184337235_produce-5.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 3000,
    listPrice: 3000,
    brand: 'Summer Farms',
    avgRating: 4.9,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 10 },
    ],
    numSales: 20,
    countInStock: 30,
    description: 'Watermelon is a sweet, juicy fruit with high water content, making it hydrating and refreshing. It’s rich in vitamins A and C, low in calories, and perfect for snacking or adding to fruit salads.',
    colors: ['Green', 'Red'],
    options: [
      {
        name: "1 piece",
        price: 3000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732184338/ahisi/1732184337235_produce-5.jpg",
        countInStock: 30,
      },
      {
        name: "Half",
        price: 1500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732184338/ahisi/1732184337235_produce-5_half.jpg",
        countInStock: 15,
      },
    ],
    reviews: [],
  },
  {
    name: 'Irish Potato',
    slug: toSlug('Irish Potato'),
    category: 'Tubers',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732430067/ahisi/1732430066821_produce-1.png", "https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fpotato&psig=AOvVaw2tkfvzxPIwLRBqu5HtIIBi&ust=1738406948684000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPjXp9rkn4sDFQAAAAAdAAAAABAE", "https://t4.ftcdn.net/jpg/02/75/77/89/360_F_275778955_xxJe5fQvDy5oXbjupdJ162zLwU4sf3kT.jpg"],
    tags: ['new-arrival', "best-seller"],
    isPublished: true,
    price: 4000,
    listPrice: 4000,
    brand: 'Local Farm',
    avgRating: 4.5,
    numReviews: 6,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 3 },
    ],
    numSales: 10,
    countInStock: 25,
    description: 'Irish potatoes are rich in carbohydrates, fiber, and vitamins. They are versatile in cooking and are used in dishes like mashed potatoes, fries, and stews. The product is sourced from Jos.',
    colors: ['Brown'],
    options: [
      {
        name: "1kg",
        price: 4000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430067/ahisi/1732430066821_produce-1.png",
        countInStock: 25,
      },
      {
        name: "2kg",
        price: 7500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430067/ahisi/1732430066821_produce-1_2kg.png",
        countInStock: 15,
      },
    ],
    reviews: [],
  },
  {
    name: 'Garlic ',
    slug: toSlug('Garlic)'),
    category: 'General',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732540256/ahisi/1732540256046_produce-30.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 7000,
    listPrice: 7000,
    brand: 'Local Farm',
    avgRating: 4.7,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 4 },
    ],
    numSales: 12,
    countInStock: 30,
    description: 'Garlic is a flavorful, aromatic bulb used in cooking and known for its health benefits, such as boosting immunity and supporting heart health.',
    colors: ['White'],
    options: [
      {
        name: "1kg - 22pcs",
        price: 7000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732540256/ahisi/1732540256046_produce-30.jpg",
        countInStock: 30,
      },
      {
        name: "500g - 11pcs",
        price: 3500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732540256/ahisi/1732540256046_produce-30_500g.jpg",
        countInStock: 20,
      },
    ],
    reviews: [],
  },
  {
    name: 'Ginger',
    slug: toSlug('Ginger'),
    category: 'General',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732430259/ahisi/1732430259444_produce-27.jpg"],
    tags: ['todays-deal'],
    isPublished: true,
    price: 5000,
    listPrice: 5000,
    brand: 'Local Farm',
    avgRating: 4.6,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 4 },
    ],
    numSales: 15,
    countInStock: 40,
    description: 'Ginger is known for its spicy flavor and health benefits, including aiding digestion and reducing inflammation. It is used in cooking, baking and beverages.',
    colors: ['Beige'],
    options: [
      {
        name: "1kg",
        price: 5000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430259/ahisi/1732430259444_produce-27.jpg",
        countInStock: 40,
      },
      {
        name: "500g",
        price: 2500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430259/ahisi/1732430259444_produce-27_500g.jpg",
        countInStock: 25,
      },
    ],
    reviews: [],
  },
  {
    name: 'Turmeric',
    slug: toSlug('Turmeric'),
    category: 'Spices and Condiments',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732430481/ahisi/1732430481369_produce-29.jpg"],
    tags: ['new-arrival'],
    isPublished: true,
    price: 3000,
    listPrice: 3000,
    brand: 'Local Farm',
    avgRating: 4.8,
    numReviews: 9,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 5 },
    ],
    numSales: 18,
    countInStock: 35,
    description: 'Turmeric is a yellow spice known for its earthy flavor and active compound, curcumin. It offers potential anti-inflammatory and antioxidant benefits and is used in cooking, natural remedies, and beauty products.',
    colors: ['Yellow'],
    options: [
      {
        name: "1kg",
        price: 3000,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430481/ahisi/1732430481369_produce-29.jpg",
        countInStock: 35,
      },
      {
        name: "500g",
        price: 1500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430481/ahisi/1732430481369_produce-29_500g.jpg",
        countInStock: 20,
      },
    ],
    reviews: [],
  },
  {
    name: 'Hibiscus',
    slug: toSlug('Hibiscus'),
    category: 'Vegetables',
    images: ["https://res.cloudinary.com/ahisi/image/upload/v1732430647/ahisi/1732430647434_produce-28.jpg"],
    tags: ['new-arrival', "best-seller"],
    isPublished: true,
    price: 2500,
    listPrice: 2500,
    brand: 'Local Farm',
    avgRating: 4.9,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 7 },
    ],
    numSales: 20,
    countInStock: 50,
    description: 'Hibiscus (Zobo leaf) is a nutrient-rich plant known for its antioxidant, vitamin C, and mineral content. It is used to make a tangy herbal drink, offering health benefits like immune support, improved digestion, and reduced blood pressure.',
    colors: ['Red'],
    options: [
      {
        name: "1kg",
        price: 2500,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430647/ahisi/1732430647434_produce-28.jpg",
        countInStock: 50,
      },
      {
        name: "500g",
        price: 1250,
        image: "https://res.cloudinary.com/ahisi/image/upload/v1732430647/ahisi/1732430647434_produce-28_500g.jpg",
        countInStock: 30,
      },
    ],
    reviews: [],
  }
]